[[ProtocolBuffersSDK]]
arch = "aarch64"
git-tree-sha1 = "cabccfd0f4867652600066556cc02b5126895715"
os = "macos"

    [[ProtocolBuffersSDK.download]]
    sha256 = "8466995df3441d912099393114237e91472d7d54d603019121de4c727bead914"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.aarch64-apple-darwin.tar.gz"
[[ProtocolBuffersSDK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b34ff3bb2e74a41ab72c313afe6524f671cb17b"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "2855fea1bb3324a92828dbf1ad5cd03b3a7e75c9763a0f5dc5ab7c5a0a42ff25"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a7fa0fc4ffc9a33c6d49c45c9634a78c64a0666"
libc = "musl"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "1eb4d0d7ea0df2a0667fcea1d66041eedd3c5ddabf50aa86db909867ef472608"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "aarch64"
git-tree-sha1 = "f66d0ac91c652bd0c68c1220e7ae43b564585c06"
os = "freebsd"

    [[ProtocolBuffersSDK.download]]
    sha256 = "2e72514ee09ad13c3c92308814106d26059757c462ada2eca52878299352c5c7"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.aarch64-unknown-freebsd.tar.gz"
[[ProtocolBuffersSDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f37f105706c162f0a1ddf646b070a740f4f785ed"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "8d7cfd3d989846f9b92581084b3ed692623f6a9d5e7bb14edfa62e5b19e459fa"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "559266cfe8fe520fa90b2d8e9b26653121dc238c"
libc = "musl"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "0e11db3066a829123c4f4f25a163b0ed322909565be43a5e36edfb3fa7b53928"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e343c6cca70d9d8514731e58e2b02794e9250bc2"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "6bce8090d82a4f7b42541a4296df74ce1a2ea0481c1c6cd712ddcd7255b02bf0"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "002152966d88171c396dda55f4fe98d6a88af7f3"
libc = "musl"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "fb46a07d3b7185eb0f491911d08b2bd7d3695c2d1fb82a7d0ddf234bbda2e969"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "681422484cc3192f47d12b2be4d7b601f50c2327"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "04885ee3c3fd54bca79505c91ba6f187eb4f9dd174db273382c4a333bca9ea7f"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.i686-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acec88922f6f8b33d88d4154a0a7d884d75d221c"
libc = "musl"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "5b2d29d2c8460938ae41035eb0d4eff468783abbb8c236702d2ad6a09c45e531"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.i686-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42aaa1f594fb1332dc609274aaea849748632e9b"
os = "windows"

    [[ProtocolBuffersSDK.download]]
    sha256 = "45b7971ade2a72b05b7b989559336d179621e590d931c0f09676258332d0aff2"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d0facfb7e9b9e60fcfbfa8ec6f30c17b7bba4e5"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "035abf0121638b47968c04ff3560459edfa163a68a8ba7804caf06bb9fdccbfd"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "449345aa8be1e07dfd4416336ae3f7cf93d05251"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "94d95409b8a46f5e2b6867315e8e007aeac56cc12164edfd349eaa97f90ce01f"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.riscv64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "x86_64"
git-tree-sha1 = "36f93aab6f2c65a47679df5e3b7285b46222fe99"
os = "macos"

    [[ProtocolBuffersSDK.download]]
    sha256 = "14a8b47328cfa60f0f15e8e03a08b849c02c59987149f9a31e3ab244f7fbf1ab"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.x86_64-apple-darwin.tar.gz"
[[ProtocolBuffersSDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "322c427c4cf7a8c1fbeadb2b461880cafeb14fe8"
libc = "glibc"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "0176b1cc2dc8f81790ec832210d161c9e4f063960128d852623afd0d4127f607"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a432fef06c02f9602bcd8048d35251f3f946f2ef"
libc = "musl"
os = "linux"

    [[ProtocolBuffersSDK.download]]
    sha256 = "b3541c789fecdb6390bb8fcd93da1236071a9395eb1184843e02264ad6b7b92d"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffersSDK]]
arch = "x86_64"
git-tree-sha1 = "dc49544203c74de8e4622ca08e173277d260c77b"
os = "freebsd"

    [[ProtocolBuffersSDK.download]]
    sha256 = "6b2e995b3f67cc732a24f973d720be222fd8c560d505a37758f03d2a4b47a520"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.x86_64-unknown-freebsd.tar.gz"
[[ProtocolBuffersSDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b109251bd6abc7fe47b10bc7a67f6324762fd606"
os = "windows"

    [[ProtocolBuffersSDK.download]]
    sha256 = "784c82b7347455d9c831e710204a2e848be28d30d6c02d001cc99da43418dc0e"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffersSDK_jll.jl/releases/download/ProtocolBuffersSDK-v3.16.1+0/ProtocolBuffersSDK.v3.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
